version: '3'

services:
  db:
    image: postgres:16.2
    container_name: txn-transaction-db
    environment:
      LANG: en_US.utf8
      POSTGRES_DB: txn-transaction-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
      PGPORT: 5432
    ports:
      - "8201:5432"
    healthcheck:
      test: pg_isready -U postgres