quarkus:
  hibernate-orm:
    database:
      generation: none
    dialect: org.hibernate.dialect.PostgreSQLDialect
    physical-naming-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

  liquibase:
    migrate-at-start: true
    change-log: db/liquibase-changelog.xml