quarkus:
  hibernate-orm:
    database:
      generation: none
    dialect: org.hibernate.dialect.PostgreSQLDialect
    physical-naming-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

  liquibase:
    change-log: db/liquibase-changelog.xml
    clean-at-start: true

  smallrye-openapi:
    path: /openapi