quarkus:
  http:
    port: 8200
  datasource:
    db-kind: postgres
    username: postgres
    password: postgres
    jdbc:
      url: jdbc:postgresql://localhost:8201/txn-transaction-db
      driver: org.postgresql.Driver

  liquibase:
    clean-at-start: true

kafka:
  bootstrap:
    servers: localhost:9092