quarkus:
  datasource:
    db-kind: postgres
    username: postgres
    password: postgres
    jdbc:
      url: jdbc:postgresql://localhost:5433/txn-transaction-api
      driver: org.postgresql.Driver