quarkus:
  hibernate-orm:
    database:
      generation: none
    dialect: org.hibernate.dialect.PostgreSQLDialect
    physical-naming-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

  liquibase:
    change-log: db/liquibase-changelog.xml
    migrate-at-start: true

  smallrye-openapi:
    path: /openapi

mp:
  messaging:
    incoming:
      accounts:
        failure-strategy: delayed-retry-topic
        connector: smallrye-kafka
        auto:
          offset:
            reset: earliest
      assets:
        failure-strategy: delayed-retry-topic
        connector: smallrye-kafka
        auto:
          offset:
            reset: earliest
      prices:
        failure-strategy: delayed-retry-topic
        connector: smallrye-kafka
        auto:
          offset:
            reset: earliest